[package]
name = "glongge-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0.68", features = ["full"] }
quote = "1.0.36"
proc-macro2 = "1.0.86"

[lib]
proc-macro = true
